# src/eda.py

import pandas as pd

from src.utils import show_banner

# --- Evaluation Data Analysis ---

"""
Create a new column in the DataFrame called 'mistral_response' and populate it with responses generated by applying the 
'generate_mistral_response' function to each 'narrative' in the DataFrame and prepare the mistral_response_cleaned 
column using extract_category function.
"""

def show_overview(df: pd.DataFrame) -> None:
    show_banner("Data Overview:")

    # --- Data Overview --- #
    print('First 10 rows of data:')
    print(df.head())

    print('Last 10 rows of data:')
    print(df.tail())

    print(f'Data Shape: {df.shape}')
    print(f'Data Information: {df.info()}')

    # Display mean, median, min, max.
    print(f'Data Description: {df.describe().T}')

    # Check for duplicate values.
    print(f'Checking for duplicate values: {df.duplicated().sum()}')

    # Check for null values.
    print(f'Checking for null values: {df.isnull().sum()}')
